sudo: true

language: python

python:
  - 3.5

install:
  - pip3 install -r requirements.txt
  - python3 setup.py install

script:
  - wget ("http://www.shaghighi.ir/Energy-Calculator/files/test.ref")
  - python3 -m energycalc test
after_success:
  - codecov